
# This is the WAF script for building the servotron server, utilities,
# and tests.

APPNAME='servitron-six'
VERSION='0.1'

scrdir='.'
blddir='build'

from platform import machine

server_sources = set([
    'server/server.cc' ])

def options(opt):
    """
    Servitron needs g++ to build the server, and PASM to generate
    the PRU code.
    """
    opt.load('compiler_c++')

def configure(conf):
    conf.find_program('pasm.{0}'.format(machine()), var='PASM', path_list='../am335x_pru_package/pru_sw/utils')
    conf.load('compiler_c++')
    conf.env.append_value('CXXFLAGS',['-O2','-Wall'])
    if machine() == 'armv7l':
       conf.env.append_value('CXXFLAGS',['-mtune=cortex-a8'])

def build(bld):
    bld(features=['cxx'],source=server_sources,name='servotrond')
    pass
